import SwiftUI
import JustAVPNCore

struct AddServerView: View {
    @EnvironmentObject var configStore: ConfigStore
    @Environment(\.dismiss) var dismiss

    @State private var name = ""
    @State private var configText = ""
    @State private var errorMessage: String?

    var body: some View {
        NavigationStack {
            Form {
                Section("Server Name") {
                    TextField("e.g. My VPS", text: $name)
                }

                Section {
                    TextEditor(text: $configText)
                        .font(.system(.body, design: .monospaced))
                        .frame(minHeight: 200)
                } header: {
                    Text("WireGuard Config")
                } footer: {
                    Text("Paste the full client .conf file generated by the server")
                }

                if let errorMessage {
                    Section {
                        Text(errorMessage)
                            .foregroundStyle(.red)
                    }
                }
            }
            .navigationTitle("Add Server")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Add") { addServer() }
                        .disabled(name.isEmpty || configText.isEmpty)
                }
            }
        }
    }

    private func addServer() {
        // Extract private key from config before parsing
        var privateKey = ""
        for line in configText.components(separatedBy: .newlines) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("PrivateKey") {
                let parts = trimmed.split(separator: "=", maxSplits: 1)
                if parts.count == 2 {
                    privateKey = parts[1].trimmingCharacters(in: .whitespaces)
                }
            }
        }

        guard !privateKey.isEmpty else {
            errorMessage = "Config must contain a PrivateKey"
            return
        }

        guard let config = ServerConfig.fromWireGuardConfig(configText, name: name) else {
            errorMessage = "Invalid WireGuard config. Ensure it has [Interface] and [Peer] sections."
            return
        }

        configStore.addServer(config, privateKey: privateKey)
        dismiss()
    }
}
